[build]
builder = "NIXPACKS"
buildCommand = "apt-get update && apt-get install -y openssl && npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 